# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/budgeting_tools',
                'doc_host': 'https://jairuspace.github.io',
                'git_url': 'https://github.com/jairuspace/budgeting_tools',
                'lib_path': 'budgeting_tools'},
  'syms': { 'budgeting_tools.budget_utils': { 'budgeting_tools.budget_utils.get_avg_monthly_spend': ( 'budget_utils.html#get_avg_monthly_spend',
                                                                                                      'budgeting_tools/budget_utils.py'),
                                              'budgeting_tools.budget_utils.get_budgeted_balance': ( 'budget_utils.html#get_budgeted_balance',
                                                                                                     'budgeting_tools/budget_utils.py'),
                                              'budgeting_tools.budget_utils.get_cash_balance': ( 'budget_utils.html#get_cash_balance',
                                                                                                 'budgeting_tools/budget_utils.py'),
                                              'budgeting_tools.budget_utils.get_transactions': ( 'budget_utils.html#get_transactions',
                                                                                                 'budgeting_tools/budget_utils.py')},
            'budgeting_tools.emergency': { 'budgeting_tools.emergency.get_emergency_fund_status': ( 'emergency.html#get_emergency_fund_status',
                                                                                                    'budgeting_tools/emergency.py')},
            'budgeting_tools.utils': {'budgeting_tools.utils.monthdelta': ('utils.html#monthdelta', 'budgeting_tools/utils.py')}}}
