# Autogenerated by nbdev

d = { 'settings': { 'branch': 'main',
                'doc_baseurl': '/budgeting_tools',
                'doc_host': 'https://jairuspace.github.io',
                'git_url': 'https://github.com/jairuspace/budgeting_tools',
                'lib_path': 'budgeting_tools'},
  'syms': {'budgeting_tools.core': {'budgeting_tools.core.foo': ('core.html#foo', 'budgeting_tools/core.py')}}}
