# AUTOGENERATED! DO NOT EDIT! File to edit: ../nbs/utils.ipynb.

# %% auto 0
__all__ = ['monthdelta']

# %% ../nbs/utils.ipynb 2
import datetime
import pandas as pd

# %% ../nbs/utils.ipynb 4
def monthdelta(date: datetime.date, delta: int) -> datetime.date:
    """Function to add/subtract a certain number of months from a given date
    eg if it is June I want to go back exactly 3 months"""
    return (date + pd.DateOffset(months=delta)).date()
